[package]
name = "gfx_test"
version = "0.1.0"
authors = ["Mattish <mattishd@gmail.com>"]

[dependencies]
glium = "*"
time = "*"
image = "*"

[dependencies.vecmath]
git = "https://github.com/PistonDevelopers/vecmath"
